sudo: required
services:
  - docker
before_install:
  - docker build -t alexis59495/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true alexis59495/react-test npm test

after_success:
  - docker build -t alexis59495/multi-client ./client
  - docker build -t alexis59495/multi-nginx ./nginx
  - docker build -t alexis59495/multi-server ./server
  - docker build -t alexis59495/multi-worker ./worker
  # Log in in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push alexis59495/multi-client
  - docker push alexis59495/multi-nginx
  - docker push alexis59495/multi-server
  - docker push alexis59495/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-430728256548'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY